# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# preprocess_autogen.py
# Created on: 2015-04-24 01:14:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: preprocess_autogen <Input_Raster> <Output_Extent> <Output_Coordinate_System> <Output_Cell_Size> <Output_Raster> 
# Description: 
# Clip the input raster to the given extent (filling in NoData with 0 if necessar), resample and project the input raster, then linearly normalize it to [0-1].
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Script arguments
Input_Raster = arcpy.GetParameterAsText(0)

Output_Extent = arcpy.GetParameterAsText(1)

Output_Coordinate_System = arcpy.GetParameterAsText(2)

Output_Cell_Size = arcpy.GetParameterAsText(3)

Output_Raster = arcpy.GetParameterAsText(4)

# Local variables:
Output_Raster_Dataset = Output_Coordinate_System
Clipped_Raster = Output_Extent

# Process: Clip
arcpy.Clip_management(Input_Raster, "", Clipped_Raster, Output_Extent, "", "NONE", "NO_MAINTAIN_EXTENT")

# Process: Project Raster
arcpy.ProjectRaster_management(Clipped_Raster, Output_Raster_Dataset, Output_Coordinate_System, "NEAREST", Output_Cell_Size, "", "", "")

# Process: Raster Calculator
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = ""
arcpy.gp.RasterCalculator_sa("Con(IsNull(\"%Output Raster Dataset%\"), 0, (\"%Output Raster Dataset%\" - \"%Output Raster Dataset%\".minimum) / (\"%Output Raster Dataset%\".maximum - \"%Output Raster Dataset%\".minimum))", Output_Raster)
arcpy.env.extent = tempEnvironment0

